(ns hyperphor.ellum.extend
  "Generate Clojure functions on demand via the LLM, caching the generated
  source so each function is only generated once.

  (defextend (update-packages []) \"Update all outdated dependencies\")

  defines `update-packages` immediately, right there: the body is written by
  the LLM on the spot, persisted to `generated-file`, and eval'd into
  `hyperphor.ellum.generated`. On a later call to `defextend` with the same
  name -- a re-eval of the same form, or a future process once
  `generated-file` has loaded -- the cached definition is reused and the LLM
  isn't consulted again.

  Ported from `claude-extend` (mt-elisp), which shells out to the `claude`
  CLI since Emacs has no LLM client of its own; here we just call
  `hyperphor.ellum.core/query` directly."
  (:require [clojure.java.io :as io]
            [clojure.pprint :as pprint]
            [hyperphor.ellum.core :as core]
            [hyperphor.ellum.util :as util]))

(def ^:dynamic *provider*
  "Provider used to generate function bodies."
  :anthropic)

(def ^:dynamic *model*
  "Model used to generate function bodies, or nil for the provider default."
  nil)

(def generated-ns
  "Namespace that generated functions are defined in."
  'hyperphor.ellum.generated)

;; Lives next to this file, on the classpath -- resolved via classpath
;; resource rather than a hardcoded project-relative path so it doesn't
;; assume the process's cwd is the project root.
(def generated-file
  "File that accumulates functions generated by `defextend`."
  (io/file (or (some-> (io/resource "hyperphor/ellum/extend.clj") io/file .getParentFile)
               (io/file "src/clj/hyperphor/ellum"))
           "generated.clj"))

;; Map from function name (symbol) to {:arglist :description} for every
;; function `defextend` has generated (populated from `generated-file` at
;; load, and live as new functions are generated).
(defonce registry (atom {}))

(defonce ^:private loaded? (atom false))

(defn register!
  "Record NAME as defextend-generated with ARGLIST/DESCRIPTION.
  Called both live after generation and from `generated-file` itself on load."
  [name arglist description]
  (swap! registry assoc name {:arglist arglist :description description}))

(defn- ensure-generated-ns []
  (or (find-ns generated-ns)
      (let [ns (create-ns generated-ns)]
        (binding [*ns* ns] (clojure.core/refer-clojure))
        ns)))

(defn load-generated!
  "Load `generated-file` once per process, populating `registry`.
  Restores the caller's `*ns*` afterward -- the file's own `ns` form would
  otherwise leave the reader parked in `hyperphor.ellum.generated`."
  []
  (when-not @loaded?
    (when (.exists generated-file)
      (binding [*ns* *ns*]
        (load-file (str generated-file))))
    (reset! loaded? true)))

;;; Generation

(defn- build-prompt [name arglist description]
  (format "Write a single Clojure `defn` named `%s` with argument vector `%s`.

It should: %s

Output ONLY that one defn form -- no explanation, no markdown fences, no
alternate versions. Give it a short one-line docstring."
          name arglist description))

(defn- extract-defn
  "Return the first `(defn NAME ...)` form in OUTPUT, read as data.
  Tries a fenced code block first, then falls back to scanning raw text for
  the form -- the model doesn't reliably honor \"no fences/no commentary\"."
  [fname output]
  (let [candidate (first (util/extract-clojure output)) ;TODO might need to be smarter
        ]
    (when-not (and (= 'defn (first candidate))
                   (= (name fname) (name (second candidate))))
      (throw (ex-info (format "defextend: no `(defn %s ...)` found in response" name)
                      {:output output})))
    candidate))

(defn- ask-llm [name arglist description]
  (let [prompt (build-prompt name arglist description)]
    (extract-defn name (core/query *provider* prompt :model *model*))))

(defmacro ^:private with-code-pprint [& body]
  `(binding [pprint/*print-pprint-dispatch* pprint/code-dispatch]
     ~@body))

(defn- ensure-header! []
  (when-not (.exists generated-file)
    (io/make-parents generated-file)
    (spit generated-file
          (with-out-str
            (with-code-pprint
              (pprint/pprint (list 'ns generated-ns (list :require ['hyperphor.ellum.extend :as 'ext]))))
            (println)))))

(defn- persist! [name arglist description form]
  (ensure-header!)
  (spit generated-file
        (with-out-str
          (pr (list 'ext/register! (list 'quote name) (list 'quote arglist) description))
          (println) (println)
          (with-code-pprint (pprint/pprint form))
          (println))
        :append true))

(defn- read-all-forms [file]
  (with-open [rdr (java.io.PushbackReader. (io/reader file))]
    (doall (take-while some? (repeatedly #(read {:eof nil} rdr))))))

(defn- rewrite-without!
  "Rewrite `generated-file` with NAME's registration+defn removed, if present."
  [name]
  (when (.exists generated-file)
    (let [[ns-form & pairs] (read-all-forms generated-file)
          kept (remove (fn [[reg _]] (= (second reg) (list 'quote name)))
                       (partition 2 pairs))]
      (spit generated-file
            (with-out-str
              (with-code-pprint (pprint/pprint ns-form))
              (println)
              (doseq [[reg defn-form] kept]
                (pr reg) (println) (println)
                (with-code-pprint (pprint/pprint defn-form)) (println) (println)))))))

(defn- generate-and-define!
  "Ask the LLM to implement NAME/ARGLIST per DESCRIPTION, persist, and eval it.
  No-ops if NAME is already registered."
  [name arglist description]
  (when-not (contains? @registry name)
    (println (str "defextend: asking the LLM to write `" name "`..."))
    (let [form (ask-llm name arglist description)]
      (persist! name arglist description form)
      (binding [*ns* (ensure-generated-ns)]
        (eval form))
      (register! name arglist description)
      (println (str "defextend: `" name "` defined (written to " generated-file ")")))))

;;; Public API

(defn define!
  "Generate and define NAME/ARGLIST per DESCRIPTION in `hyperphor.ellum.generated`,
  unless already generated. Returns the resulting var."
  [name arglist description]
  (load-generated!)
  (cond
    (contains? @registry name)
    (ns-resolve (ensure-generated-ns) name)

    (ns-resolve (ensure-generated-ns) name)
    (throw (ex-info (str "defextend: `" name "` is already defined by something other than defextend")
                    {:name name}))

    :else
    (do (generate-and-define! name arglist description)
        (ns-resolve (ensure-generated-ns) name))))

(defmacro defextend
  "Define `(name arglist)` in `hyperphor.ellum.generated`, generating the body
  via the LLM right now if it isn't already cached in `generated-file`. This
  blocks on the API call. SIGNATURE is `(name arglist)` exactly as it would
  appear after `defn`, e.g. `(greet [name])`. Returns the resulting var."
  [signature description]
  (let [[name arglist] signature]
    `(define! '~name '~arglist ~description)))

(defn regenerate!
  "Discard the cached body of defextend function NAME and regenerate it."
  [name]
  (load-generated!)
  (if-let [{:keys [arglist description]} (@registry name)]
    (do
      (rewrite-without! name)
      (swap! registry dissoc name)
      (ns-unmap (ensure-generated-ns) name)
      (generate-and-define! name arglist description)
      (ns-resolve (ensure-generated-ns) name))
    (throw (ex-info (str "defextend: `" name "` was not generated by defextend") {:name name}))))
